---
volumes:
  dagster-postgres:
    driver: local
  io_manager:
    driver: local

x-common: &x-common
  restart: unless-stopped

services:
  rabbitmq:
    image: rabbitmq:3.8.2
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: dino
      RABBITMQ_DEFAULT_PASS: SPKKJxqHIc1OS92raTeo
      RABBITMQ_DEFAULT_VHOST: dino
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  splunk:
    <<: *x-common
    container_name: splunk
    image: dino/splunk
    build:
      context: ./docker/splunk
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
    ports:
      - 8000:8000
      # - 9997:9997S
      - 8088:8088
      - 8089:8089

  dagster-dagit:
    <<: *x-common
    container_name: dagit
    image: dino/dagster
    build:
      context: .
      dockerfile: ./docker/dagster/dev/Dockerfile
    ports:
      - 3000:3000

  dagster-daemon:
    <<: *x-common
    container_name: dagster
    image: dino/dagster
    build: 
      context: .
      dockerfile: ./docker/dagster/dev/Dockerfile
    command: "dagster-daemon run"
    volumes:
      - ./dino:/opt/dino/dino
      - ./presets:/opt/dino/presets
      - ${ROOT_FOLDER}:/DINO_ROOT
      - io_manager:/var/local/dino_io_managers

  worker:
    <<: *x-common
    image: dino/dagster
    build: 
      context: .
      dockerfile: ./docker/dagster/dev/Dockerfile
    command: "dagster-celery worker start -y celery_config.yaml -A dagster_celery.app"
    volumes:
      - ./dino:/opt/dino/dino
      - ./presets:/opt/dino/presets
      - ${ROOT_FOLDER}:/DINO_ROOT
      - io_manager:/var/local/dino_io_managers


  dagster-postgres:
    <<: *x-common
    container_name: postgres
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=ZwRQ1XCLT8VdfjlC43gY
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
